// <auto-generated />
using System;
using CoachingAutomationExcel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coacing_Automation_Excel.Migrations
{
    [DbContext(typeof(CoachingDbContext))]
    [Migration("20260606192724_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CoachingAutomationExcel.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("CoachingAutomationExcel.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttendanceEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BroadcastEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExamsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FeesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramBotToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwilioNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwilioSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwilioToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CoachingAutomationExcel.Entities.NotificationStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationStatistics");
                });

            modelBuilder.Entity("CoachingAutomationExcel.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
